### PR TITLE
Update build.py

### PR DESCRIPTION
**Pull request by Daynvheur**
Added top-script `#UPDATE PATH` section.
Path are now constructed (`xyzDir`+`dllName`) for more name reuse.

### CODE REVIEW

**Comment by jemand771** [comment]
this isn't ideal. if we're gonna restructure it like you suggest, we should use `pathlib.Path`s for at least the dll - that way we can get the file name and parent dir from one variable :)

also I'm not sure if I like the stacklands exe auto-detection. it's a nice idea but it introduces "magic" that's not obvious and might lead to weird situations (user configures stacklands path, script auto-detects the exe _somewhere else_, kills it, and then launches the exe that it found (wrong) instead of the configured one)

However, I could see us finding the process by its exe path instead of just the name. that way, it's "smart" like you intended, but not magic
@Cyber28 thoughts? (especially on the last part)

**Comment by jemand771** [comment]
either way, since this pr is already kind of a mess (multiple unrelated changes) I'll probably split it up and co-author you wherever applicable ^^

**Comment by Cyber28** [comment]
Not sure about the smart exe detection part, but if it works and is user-friendly enough, I don't mind!

**Comment by Daynvheur** [comment]
Why was it closed?
The exe part is nothing special, maybe it's possible to discard this psutils line?

**Comment by jemand771** [comment]
@Daynvheur just as a quick follow-up:
the idea about finding the stacklands process via its exe instead of its name doesn't actually work since not all processes _have_ an executable (I'm guessing this has something to do with process 0/1 being something like the "init" process)

Just thought I'd let you know since the idea kinda came from this PR

**Comment by Daynvheur** [comment]
I don't care that much about one particular line of code, knowing it's a psutils tool that would have provided the execution path of the process. (No, it's not a mandatory ".exe", nor did I tested it on Linux to check if any process has its execution path working.)

**Pull request closed without merging**
